'\" t
.\"     Title: polkit-default-privs
.\"    Author: Ludwig Nussel <ludwig.nussel@suse.de>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 02/04/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "POLKIT\-DEFAULT\-PRI" "5" "02/04/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
polkit-default-privs \- default privilege settings
.SH "DESCRIPTION"
.sp
The files /etc/polkit\-default\-privs\&.* are line based and space delimited\&.
.sp
Lines starting with # are comments\&.
.sp
The first column lists the privilege names
.sp
The second column lists the PolicyKit default setting\&. A default setting consists of three values separated by colon\&. The meanings from left to right are are \fIany user\fR, \fIuser not on the active console\fR and \fIuser on the active console\fR\&. If all three values are the same only one value may be specified without colon to shorten the line\&.
.SH "FILES"
.sp
/etc/polkit\-default\-privs\&.local
.sp
/etc/polkit\-default\-privs\&.restrictive
.sp
/etc/polkit\-default\-privs\&.standard
.sp
/etc/polkit\-default\-privs\&.easy
.sp
/etc/polkit\-default\-privs\&.d/*
.SH "SEE ALSO"
.sp
set_polkit_default_privs(8), PolicyKit(8)
.SH "REPORTING BUGS"
.sp
Report bugs to https://bugzilla\&.suse\&.com/
.SH "AUTHOR"
.PP
\fBLudwig Nussel\fR <\&ludwig\&.nussel@suse\&.de\&>
.RS 4
Author.
.RE
