'\" t
.\"     Title: set_polkit_default_privs
.\"    Author: Ludwig Nussel <ludwig.nussel@suse.de>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 02/04/2019
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SET_POLKIT_DEFAULT_P" "8" "02/04/2019" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
set_polkit_default_privs \- set default privileges for PolicyKit
.SH "SYNOPSIS"
.sp
set_polkit_default_privs
.SH "DESCRIPTION"
.sp
The set_polkit_default_privs program installs default settings for privileges that are granted automatically to locally logged in users by polkit\&.
.SH "CONFIGURATION"
.sp
see CHECK_POLKIT_PRIVS and POLKIT_DEFAULT_PRIVS in /etc/sysconfig/security\&.
.SH "SEE ALSO"
.sp
polkit\-default\-privs(5), polkit(8)
.SH "REPORTING BUGS"
.sp
Report bugs to https://bugzilla\&.suse\&.com/
.SH "AUTHOR"
.PP
\fBLudwig Nussel\fR <\&ludwig\&.nussel@suse\&.de\&>
.RS 4
Author.
.RE
