#!/bin/bash
set -e
shopt -s nullglob
if [ $# -eq 1 ]; then
	name="$1"
else
	name="`pwd -P`"
	name=${name##*/}
	name=${name%%.*}
fi
src="$PWD"
if [ ! -d "$name/.osc" ]; then
	echo "*** Error: please check out the package:"
	echo "osc branch openSUSE:Factory $name"
	echo "ln -s home\:*\:branches\:*/$name ."
	exit 1
fi
if [ "`git --no-pager diff --name-only|wc -l`" != '0' -o "`git --no-pager diff --name-only --cached|wc -l`" != 0 ]; then
	echo "*** Error: uncomitted changes"
	echo "run 'git add file' to add files, 'git commit -a' to commit changes"
	if [ ! -t 0 ]; then
		exit 1
	fi
	echo "Do you want to continue anyway (y/n)?"
	echo "The resulting package will not contain the uncommited changes."
	while true; do
		read CONT
		if [ "$CONT" = "y" ]; then
			break
		else
			exit 1
		fi
	done
fi
cd "$name"
echo "osc up"
osc up
cd "$src"
"$src"/obs/mkchanges "$name/$name".changes | tee "$name"/.changes
#test ! -s $name/.changes || git push
for i in *.bz2; do
	/bin/rm -vi "$i"
done
cd "$src"
"$src"/obs/mktar
mv *bz2 "$name"
cd "$name"
osc vc "$name".changes .changes && rm -f .changes
cd "$src"
if [ -n "`git rev-list remotes/origin/master..HEAD`" ]; then
	pushed=
	if ! grep -q refs/heads/master .git/HEAD; then
		echo "Warning: not on master branch"
	elif read -p "push changes now? (Y/n) "; then
		if [ -z "$REPLY" -o "${REPLY#y}" != "$REPLY" ]; then
			git push && pushed=1 || true
		fi
	fi
	if [ -z "$pushed" ]; then
		echo "*** Warning: changes not pushed!"
	else
		cd "$name"
		osc ci
	fi
fi
