#! /bin/bash
# This module sets policykit default permissions
# Copyright (C) 2008 SUSE Linux Products GmbH, Nuernberg, Germany.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Based on SuSEconfig.permissions
#
# Author: Ludwig Nussel <lnussel@suse.de> 2008
#

shopt -s nullglob

. /etc/sysconfig/security || exit 1

if [ -z "$POLKIT_DEFAULT_PRIVS" ]; then
    case "$PERMISSION_SECURITY" in
        *secure*|*paranoid*) POLKIT_DEFAULT_PRIVS="restrictive" ;;
        *) POLKIT_DEFAULT_PRIVS="standard" ;;
    esac
fi

mode=""
case "$CHECK_POLKIT_PRIVS" in
    set|"") mode="-set" ;;
    warn) ;;
    no) exit 0 ;;
    *) echo "invalid value '$CHECK_POLKIT_PRIVS' for \$CHECK_POLKIT_PRIVS, using 'set'" >&2; mode="-set" ;;
esac

# collect files that contain permission specifications
# we need to use a useful order
#
# 1. common privileges file (we have none yet)
files=()

# 2. easy, standard, restrictive as those are defined by SUSE
for level in $POLKIT_DEFAULT_PRIVS; do
    case "$level" in
        easy|standard|restrictive)
            if [ -e /usr/share/polkit-default-privs/profiles/$level ]; then
                files+=("/usr/share/polkit-default-privs/profiles/$level")
            fi
        ;;
        *)
            echo "invalid value '$level' in POLKIT_DEFAULT_PRIVS in /etc/sysconfig/security, ignoring" 1>&2
        ;;
    esac
done

# 3. package specific privileges
# The /usr/share is the new and preferred path, /etc is deprecated but still supported for the moment.
pkgfiles=()
for f in /usr/share/polkit-default-privs/package-overrides.d/* /etc/polkit-default-privs.d/* ; do
    base="${f##*/}"
    profile="${base%%.*}"
    if ! [[ " ${pkgfiles[*]} " == *" ${profile} "* ]] ; then
        pkgfiles+=("${profile}")

        for prefix in /usr/share/polkit-default-privs/package-overrides.d/ /etc/polkit-default-privs.d/ ; do
            file="${prefix}${profile}"
            [ -e "$file" ] && files+=("$file")
            for level in $POLKIT_DEFAULT_PRIVS; do
                [ -e "$file.$level" ] && files+=("$file.$level")
            done
            # do not process /etc if we found a file in /usr/share
            [ -e "$file" ] && break
        done
    fi
done

# 4. central privileges files with user defined level excl 'local'
for level in $POLKIT_DEFAULT_PRIVS; do
    if [ -e "/usr/share/polkit-default-privs/profiles/$level" ] && [[ "$level" != local ]]; then
        files+=("/usr/share/polkit-default-privs/profiles/$level")
    fi
done

[ -e "/etc/polkit-default-privs.local" ] && files+=("/etc/polkit-default-privs.local")

chkstat-polkit "$mode" "${files[@]}"
